login:
  type: Zend_Controller_Router_Route_Static
  route: login
  defaults:
    module: users
    controller: login
    action: index
logout:
  type: Zend_Controller_Router_Route_Static
  route: logout
  defaults:
    module: users
    controller: login
    action: logout
recoverPassword:
  type: Zend_Controller_Router_Route_Regex
  route: recover-password/([\w]{32})
  defaults:
    module: users
    controller: login
    action: recover-password
  map:
    hash: 1
cancelRecoveryPassword:
  type: Zend_Controller_Router_Route_Regex
  route: cancel-recovery-password/([\w]{32})
  defaults:
    module: users
    controller: login
    action: cancel-recovery-password
  map:
    hash: 1
forgetPassword:
  type: Zend_Controller_Router_Route_Static
  route: forget-password
  defaults:
    module: users
    controller: register
    action: forget-password