login:
  type: Zend_Controller_Router_Route_Static
  route: login
  defaults:
    module: users
    controller: login
    action: index
logout:
  type: Zend_Controller_Router_Route_Static
  route: logout
  defaults:
    module: users
    controller: login
    action: logout

recoverPassword:
  type: Zend_Controller_Router_Route
  route: recover-password/:hash
  defaults:
    module: users
    controller: login
    action: recover-password

cancelPasswordRecoveryAction:
  type: Zend_Controller_Router_Route
  route: cancel-password-recovery/:hash
  defaults:
    module: users
    controller: login
    action: cancel-password-recovery
    
forgetPassword:
  type: Zend_Controller_Router_Route_Static
  route: forget-password
  defaults:
    module: users
    controller: register
    action: forget-password