dashboard:
  translate-managment:
    label: Translate
    uri:
    pages:
      create:
        label: Create
        module: translate
        controller: management
        action: create
        route: default
      edit:
        label: Edit
        module: translate
        controller: management
        action: index
        route: default
      build:
        label: Build
        module: translate
        controller: management
        action: build
        route: default