dashboard:
  commentsmanagment:
    label: Comments
    uri:
    class: comment
    order: 95
    pages:
      aliases:
        label: View Aliases
        module: comments
        controller: aliases
        action: index
        route: default