menumanagment:
  label: Menu
  uri:
  pages:
    create:
      label: Create Menu Item
      module: menus
      controller: management
      action: create
      route: default
    manage:
      label: Manage Menu
      module: menus
      controller: management
      action: index
      route: default
      