staticpages:
  label: Pages
  uri:
  pages:
    create:
      label: Create
      module: pages
      controller: management
      action: create
      route: default
    edit:
      label: Edit
      module: pages
      controller: management
      action: index
      route: default
    uploads:
      label: Uploads Manager
      module: pages
      controller: uploads
      action: index
      route: default