dashboard:
  forummanagment:
    label: Forum
    uri:
    pages:
      create:
        label: Create New Post
        module: forum
        controller: management
        action: create
        route: default
      edit:
        label: Edit Posts
        module: forum
        controller: management
        action: index
        route: default
default:
  forum:
    label: Forum
    route: default
    module: forum
    controller: index
    action: index