production:
  phpSettings:
    display_startup_errors: false
    display_errors: false
    date:
      timezone: Europe/Kiev
  includePaths:
    library: APPLICATION_PATH/../library
  pluginPaths:
    Core_Application_Resource: Core/Application/Resource
  bootstrap:
    path: APPLICATION_PATH/Bootstrap.php
    class: Bootstrap
  appnamespace: Application
  autoloadernamespaces:
    - Core
  resources:
    frontController:
      moduleDirectory: APPLICATION_PATH/modules
      moduleControllerDirectoryName: controllers
      defaultControllerName: index
      defaultAction: index
      defaultModule: default
      baseurl: /
      env: APPLICATION_ENV
      params:
        prefixdefaultmodule: true
        displayExceptions: false
        
      actionhelperpaths:
        Helper: APPLICATION_PATH/helpers

      plugins:
        translate:
          class: Core_Controller_Plugin_Translate
          stackindex: 20
          options:
            default: en
            locales:
              ru: ru_RU
              ua: uk_UA
              en: en_GB
              us: en_US
            adapter: gettext
            content: APPLICATION_PATH/../data/languages/
            scan: filename
            disableNotices: on
            logUntranslated: off
            logMessage: Undefined message '%message%' in '%locale%'
            logPath: APPLICATION_PATH/../data/logs/lang.log

        acl:
          class: Core_Controller_Plugin_Acl
          stackindex: 30
          options:
            config: acl
            allowAll: on
            denied:
              module: default
              controller: error
              action: denied
            role: guest
            cache: on
            
        routes:
          class: Core_Controller_Plugin_Routes
          stackindex: 40
          options:
            config: routes
            cache: on

        navigation:
          class: Core_Controller_Plugin_Navigation
          stackindex: 50
          options:
            config: navigation
            section: dashboard
            cache: on
            
    modules:
    db:
      adapter: pdo_mysql
      params:
        host: hippo.nixsolutions.com
        username: p_zfc
        password: zfc
        dbname: p_zfc
        charset: utf8
      isDefaultTableAdapter: true
    layout:
      layout: default/layout
      layoutPath: APPLICATION_PATH/layouts/scripts/
    session:
      save_path: APPLICATION_PATH/../data/session
    auth: true
    mail:
      transport:
        type: Zend_Mail_Transport_Smtp
        host: stubmail.nixsolutions.com
        port: 2500
      defaultFrom:
        email: zfc@nixsolutions.com
        name: ZFCore Webmaster
  view:
    title: ZFCore
    doctype: HTML5
    encoding: UTF-8

testing:
  _extends: production
  phpSettings:
    display_startup_errors: true
    display_errors: true
  resources:
    db:
      params:
        host: elephant.nixsolutions.com
        username: p_zfc2
        dbname: p_zfc2
        persistent: true
    frontController:
      plugins:
        acl:
          options:
            allowAll: off

development:
  _extends: production
  phpSettings:
    display_startup_errors: true
    display_errors: true
    error_reporting: E_ALL|E_STRICT

  resources:
    frontController:
      plugins:
        debug:
          class:Core_Controller_Plugin_Debug
    db:
      params:
        profiler:
          enabled: true
          class: Zend_Db_Profiler_Firebug
